### ISSUE TITLE
Exploring the Absence of a Planner Manager in the MRS Stack: Design Choice or Oversight?

### ISSUE THREAD

**Issue by zeeshanns** [ctu-mrs/mrs_uav_core#2]
I have a question regarding planner management. The MRS stack appears to offer a highly general and well-structured modular design, especially with the use of plugins and managers for elements like the controller (control manager) and estimation manager. However, it seems to lack a planner manager. Was this an intentional design choice, or is there a specific reason for not including a planner manager?

Adding a planner manager could provide more flexibility in selecting the planner and its corresponding controller.

**Comment by klaxalk** [comment]
Hey, good question! The idea of a planner manager definitely came do my mind. However, several challenges prevented us from implementing it to this day:

- uncertainty about the API (this is much more complex question than with estimators, trackers and controllers...) and the complexity of the problem
- the severe lack of human and time resources: we are now barely able to maintain the status quo of the system
- the preparations for ROS2 transition: we have halted all developement of new features till we transfer to ROS2

But it is on our list, so hope for the best :-).

**Comment by zeeshanns** [comment]
"Thank you, @klaxalk, for your detailed response! I understand the current limitations and appreciate the roadmap insights. I’m exploring the idea of creating a 'bank of planners' within the MRS stack, allowing for a specific planner to be selected at runtime alongside its corresponding controller, depending on the mission requirements or environment.

I have a few more specific questions to help guide my design:

    Planner Manager Design: Do you think it would make sense for the planner manager to dynamically call planner plugins on the fly? For example, would you recommend designing it in a way that enables runtime planner selection while ensuring compatibility with the existing control manager?

    Controller Coordination: Since I want different planners to use different controllers, would it be advisable for the control manager to also dynamically call the relevant controller plugin when a new planner is selected? Or, is there a different approach you’d suggest for managing planner-controller pairs?

    API and Interface Suggestions: Given the API complexity, do you have any thoughts on structuring the planner manager’s interface to keep it modular and compatible with MRS’s existing architecture?

    ROS 2 Transition: Finally, if you have insights on ensuring ROS 2 compatibility or any future-proofing measures, they would be incredibly valuable as I build this out.

Thank you again for your time and any guidance you can share—I’d be happy to contribute to the MRS stack in return if there’s an opportunity!"

**Comment by klaxalk** [comment]
Hey, thanks for the feedback!

I think that the Planning manager's connection to the MRS system would be pretty similar to the current ties the "MRS Octomap Planner" already has and these are not very constraining connections. There is the outgoing API from the planner / planning manager:
* desired path going into the trajectory generation
* emergency hover() being called into the control manager
and the ingoing API:
* TFs
* a MAP
* drone's trajectory prediction which is used for fast collision detection and prevention.

Regarding the ROS2 transition and future proofness.. On one hand I would say that not relying on ROS APIs too much and making sure you software is as much agnostic to ROS as possible. On the other hand, since we are talking about a plugin-based system, it is hard to really intie it from the underlying ROS interfaces which provide the plugin libraries... So I don't have a clear advice here :-(.

**Comment by zeeshanns** [comment]
"Thank you, @klaxalk, for the clarification and additional insights!

Regarding your mention of the 'MRS Octomap Planner' and its connections to the MRS system, I noticed that there are two repositories:

    [mrs_octomap_planner](https://github.com/ctu-mrs/mrs_octomap_planner)
    [mrs_octomap_mapping_planning](https://github.com/ctu-mrs/mrs_octomap_mapping_planning)

Could you confirm which of these repositories you’re referring to when discussing the planner manager framework? This will help me align my understanding and ensure the design stays consistent with the intended structure.

Thanks again for your time and support!"
